### ISSUE TITLE
Can't install nats-queue with cabal install nats-queue

### ISSUE THREAD

**Issue by jpotecki** [wayofthepie/nats-queue#1]
Can't install nats-queue with cabal install nats-queue in fedora 23 cloud base
cabal-install version 1.18.1.0
using version 1.18.1.5 of the Cabal library
GHCi, version 7.8.4

Network/Nats.hs:520:32:
    Couldn't match expected type `(t5, t6)'
                with actual type`Maybe (a, q a)'
    Relevant bindings include
      item :: t5 (bound at Network/Nats.hs:520:18)
      newq :: t6 (bound at Network/Nats.hs:520:24)
      queue :: q a (bound at Network/Nats.hs:518:19)
      popCb :: (t1, q a, t3, t4) -> m ((t1, t2, t3, t4), t)
        (bound at Network/Nats.hs:518:9)
    In the expression: popFront queue
    In a pattern binding: (item, newq) = popFront queue
Failed to install nats-queue-0.1.2.0
cabal: Error: some packages failed to install:
nats-queue-0.1.2.0 failed during the building phase. The exception was:
ExitFailure 1

**Comment by wayofthepie** [comment]
Hi @jpotecki, support for ghc 7.8.4 was dropped as part of https://github.com/ondrap/nats-queue/issues/2, details of why in that ticket. Updating to 7.10 should fix this.

I'll be looking at getting nats-queue onto [stackage](https://www.stackage.org/) soon too.

**Comment by wayofthepie** [comment]
In fact, I am wrong! 

I didn't notice this was version 0.1.2.0 of nats-queue, this supports ghc 7.8.4 so the error you are getting is a different one.

The actual cause of the error is to do with the version of dequeue installed, **nats-queue-1.2.0** requires **dequeue-0.1.5**. The dependency for **dequeue** on hackage for **nats-queue-1.2.0** is unbounded, I can set this to be 1.5.0 explicitly, will do this as soon as I get a chance. You should also be able to explicitly install **dequeue-1.5.0**.

**Comment by wayofthepie** [comment]
Closing as this shouldn't be an issue anymore, the dequeue dependency in nats-queue 0.1.2.0 was constrained.
